version: '2'
template:
  name: "BudBlocks Business Network"
  description: "Deploy the BudBlocks Business Network to IBM Cloud."
  required:
    - build
    - repo
    - deploy

toolchain:
  name: 'budblocks-business-network-{{timestamp}}'

services:
  repo:
    service_id: githubpublic
    parameters:
      repo_name: 'budblocks-{{timestamp}}'
      repo_url: 'https://github.com/BudBlocks/Composer'
      type: existing
      has_issues: true
      enable_traceability: true
  build:
    service_id: pipeline
    parameters:
      services:
        - repo
      name: '{{services.repo.parameters.repo_name}}'
      ui-pipeline: true
      sin: 'test'
      configuration:
        content:
          $text: pipeline.yml
        env:
          REPO: repo
          SPACE_NAME: '{{form.pipeline.parameters.deploy-space}}'
          ORG_NAME: '{{form.pipeline.parameters.deploy-organization}}'
          REGION_ID: '{{form.pipeline.parameters.deploy-region}}'
        execute: true

form:
  pipeline:
    # parameters:
      # deploy-region: 'ibm:yp:us-south'
    schema:
      $ref: deploy.json
